theme: minima
title: Fei' Learning Time
author: FeiLiezel
email: fei.liezel@gmail.com
description: Learning Github pages
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
